# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d45c21819f4d854eca54f5c94431d08137466fb5e5dafb154695461a6952b91c5ed23f0552530b3eb0c04ad263a8ba136c4706bb1117721aff7c888dd7661ac4

test:
  secret_key_base: fd0c07bbd3c22787cb5fa589aa7e73bc52c8779f67d9d8d25145cf08421d8df935f80d44b1972d967bb6c16942bbe34a201ba9fc465f85c49d2f9c0a8c39eafb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
